META_FILE: '/Users/chensle/PycharmProjects/gminer/run/pdf-vcs_meta.csv'
COUNT_FILE: '/Users/chensle/PycharmProjects/gminer/run/pdf-vcs_count.csv'
LOCAL_REPO: '/Users/chensle/emse/SE6356.MS1-SoftwareMaintenanceEvolutionAndRe-Engineering-F18/Projects/local_repo/peep-pdfbox'
#BRANCHES: ["1.1.x", "1.2", "1.2.x", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "2.0", "before-apache-packages", "before-maven-layout", "no-awt", "trunk", "xmpbox-refactoring"]
BRANCHES: ["1.1.x"]
START_YEAR: 2008
START_MONTH: 3
START_DAY: 1
STOP_YEAR: 2017
STOP_MONTH: 11
STOP_DAY: 1
TIME_ZONE_OFFSET: 6
